name: Build

on: [push]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Opus Source
        run: wget https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz -O opus-1.3.1.tar
      - name: Extract Opus Source
        run: tar -xf opus-1.3.1.tar  # 直接解压到当前目录
      - name: Build APK
        run: |
          cd android_app
          chmod +x gradlew
          ./gradlew assembleDebug

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Windows
        run: |
          # 修正目录名称：windows → windows_app
          cd windows_app
          cmake -B build -DCMAKE_PREFIX_PATH="libraries"
          cmake --build build --config Release